/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAssetsRouteImport } from './routes/_app/assets'
import { Route as AppBusinessesRouteImport } from './routes/_app/businesses'
import { Route as AppCollectionsRouteImport } from './routes/_app/collections'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppEmployeesRouteImport } from './routes/_app/employees'
import { Route as AppExpensesRouteImport } from './routes/_app/expenses'
import { Route as AppIncomeRouteImport } from './routes/_app/income'
import { Route as AppInvoicesRouteImport } from './routes/_app/invoices'
import { Route as AppJobsRouteImport } from './routes/_app/jobs'
import { Route as AppMarketplaceRouteImport } from './routes/_app/marketplace'
import { Route as AppOffersRouteImport } from './routes/_app/offers'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppQuotationsRouteImport } from './routes/_app/quotations'
import { Route as AppRequestsRouteImport } from './routes/_app/requests'
import { Route as AppSaccoRouteImport } from './routes/_app/sacco'
import { Route as AppSalesRouteImport } from './routes/_app/sales'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTabRouteImport } from './routes/_app/tab'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppWorkRouteImport } from './routes/_app/work'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessesRoute = AppBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsRoute = AppCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomeRoute = AppIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppOffersRoute = AppOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsRoute = AppQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppSaccoRoute = AppSaccoRouteImport.update({
  id: '/sacco',
  path: '/sacco',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTabRoute = AppTabRouteImport.update({
  id: '/tab',
  path: '/tab',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkRoute = AppWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/assets': typeof AppAssetsRoute
  '/businesses': typeof AppBusinessesRoute
  '/collections': typeof AppCollectionsRoute
  '/customers': typeof AppCustomersRoute
  '/employees': typeof AppEmployeesRoute
  '/expenses': typeof AppExpensesRoute
  '/income': typeof AppIncomeRoute
  '/invoices': typeof AppInvoicesRoute
  '/jobs': typeof AppJobsRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/offers': typeof AppOffersRoute
  '/products': typeof AppProductsRoute
  '/quotations': typeof AppQuotationsRoute
  '/requests': typeof AppRequestsRoute
  '/sacco': typeof AppSaccoRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/tab': typeof AppTabRoute
  '/users': typeof AppUsersRoute
  '/work': typeof AppWorkRoute
}
export interface FileRoutesByTo {
  '/assets': typeof AppAssetsRoute
  '/businesses': typeof AppBusinessesRoute
  '/collections': typeof AppCollectionsRoute
  '/customers': typeof AppCustomersRoute
  '/employees': typeof AppEmployeesRoute
  '/expenses': typeof AppExpensesRoute
  '/income': typeof AppIncomeRoute
  '/invoices': typeof AppInvoicesRoute
  '/jobs': typeof AppJobsRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/offers': typeof AppOffersRoute
  '/products': typeof AppProductsRoute
  '/quotations': typeof AppQuotationsRoute
  '/requests': typeof AppRequestsRoute
  '/sacco': typeof AppSaccoRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/tab': typeof AppTabRoute
  '/users': typeof AppUsersRoute
  '/work': typeof AppWorkRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/assets': typeof AppAssetsRoute
  '/_app/businesses': typeof AppBusinessesRoute
  '/_app/collections': typeof AppCollectionsRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/income': typeof AppIncomeRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/marketplace': typeof AppMarketplaceRoute
  '/_app/offers': typeof AppOffersRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/quotations': typeof AppQuotationsRoute
  '/_app/requests': typeof AppRequestsRoute
  '/_app/sacco': typeof AppSaccoRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tab': typeof AppTabRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/work': typeof AppWorkRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/businesses'
    | '/collections'
    | '/customers'
    | '/employees'
    | '/expenses'
    | '/income'
    | '/invoices'
    | '/jobs'
    | '/marketplace'
    | '/offers'
    | '/products'
    | '/quotations'
    | '/requests'
    | '/sacco'
    | '/sales'
    | '/settings'
    | '/tab'
    | '/users'
    | '/work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/assets'
    | '/businesses'
    | '/collections'
    | '/customers'
    | '/employees'
    | '/expenses'
    | '/income'
    | '/invoices'
    | '/jobs'
    | '/marketplace'
    | '/offers'
    | '/products'
    | '/quotations'
    | '/requests'
    | '/sacco'
    | '/sales'
    | '/settings'
    | '/tab'
    | '/users'
    | '/work'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/assets'
    | '/_app/businesses'
    | '/_app/collections'
    | '/_app/customers'
    | '/_app/employees'
    | '/_app/expenses'
    | '/_app/income'
    | '/_app/invoices'
    | '/_app/jobs'
    | '/_app/marketplace'
    | '/_app/offers'
    | '/_app/products'
    | '/_app/quotations'
    | '/_app/requests'
    | '/_app/sacco'
    | '/_app/sales'
    | '/_app/settings'
    | '/_app/tab'
    | '/_app/users'
    | '/_app/work'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets': {
      id: '/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/businesses': {
      id: '/_app/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof AppBusinessesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections': {
      id: '/_app/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AppCollectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/income': {
      id: '/_app/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof AppIncomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace': {
      id: '/_app/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offers': {
      id: '/_app/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AppOffersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotations': {
      id: '/_app/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AppQuotationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests': {
      id: '/_app/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sacco': {
      id: '/_app/sacco'
      path: '/sacco'
      fullPath: '/sacco'
      preLoaderRoute: typeof AppSaccoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tab': {
      id: '/_app/tab'
      path: '/tab'
      fullPath: '/tab'
      preLoaderRoute: typeof AppTabRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/work': {
      id: '/_app/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof AppWorkRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssetsRoute: typeof AppAssetsRoute
  AppBusinessesRoute: typeof AppBusinessesRoute
  AppCollectionsRoute: typeof AppCollectionsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppIncomeRoute: typeof AppIncomeRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppJobsRoute: typeof AppJobsRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppOffersRoute: typeof AppOffersRoute
  AppProductsRoute: typeof AppProductsRoute
  AppQuotationsRoute: typeof AppQuotationsRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppSaccoRoute: typeof AppSaccoRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTabRoute: typeof AppTabRoute
  AppUsersRoute: typeof AppUsersRoute
  AppWorkRoute: typeof AppWorkRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssetsRoute: AppAssetsRoute,
  AppBusinessesRoute: AppBusinessesRoute,
  AppCollectionsRoute: AppCollectionsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppIncomeRoute: AppIncomeRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppJobsRoute: AppJobsRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppOffersRoute: AppOffersRoute,
  AppProductsRoute: AppProductsRoute,
  AppQuotationsRoute: AppQuotationsRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppSaccoRoute: AppSaccoRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTabRoute: AppTabRoute,
  AppUsersRoute: AppUsersRoute,
  AppWorkRoute: AppWorkRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
